FROM python:3.8-alpine

RUN python3 -m venv /usr/share/python3/venv
RUN /usr/share/python3/venv/bin/pip install -U pip

COPY requirements.txt /mnt/
RUN /usr/share/python3/venv/bin/pip install -Ur /mnt/requirements.txt

COPY /market /mnt/
WORKDIR /mnt/
