version: '3.4'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  market:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./market:/mnt/market
    command: /usr/share/python3/venv/bin/python -m market --app-host=0.0.0.0
    environment:
      - DB_URL=postgresql+asyncpg://postgres:password@postgres:5432/postgres

volumes:
  pgdata:
