version: '3.4'

services:
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  market:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./market:/mnt/market
      - ./docker-entrypoint.dev.sh:/mnt/docker-entrypoint.dev.sh
    entrypoint: sh ./docker-entrypoint.dev.sh
    environment:
      - DB_URL=postgresql+asyncpg://postgres:password@postgres:5432/postgres

volumes:
  pgdata:
