---

- name: Gathering facts
  hosts: dev
  become: yes
  gather_facts: yes

- name: Install docker
  hosts: dev
  become: yes
  gather_facts: no
  roles:
    - docker

- name: Install market
  hosts: dev
  become: yes
  gather_facts: no
  roles:
    - market
