name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: docker://postgres:alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
    steps:
      - uses: actions/checkout@v3
      - name: Setup python3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -Ur requirements.txt
      - name: Run tests
        run: pytest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Setup python3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Build python package
        run: python setup.py sdist
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dabnd/market:0.0.1, dabnd/market:latest
          context: .
